language: java
branches:
  only:
  - master
  - develop
before_install:
- chmod +x gradlew
install: true
cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
script:
- git clone -b master https://github.com/nablarch/nablarch-ci-script.git $HOME/build-script/
  && chmod +x $HOME/build-script/travis-ci/*.sh
- $HOME/build-script/travis-ci/install-ibm-wmq-lib-7.5.sh
- $HOME/build-script/travis-ci/install-oracle-jdk6.sh
- $HOME/build-script/travis-ci/nablarch-build-nodeploy.sh
- $HOME/build-script/travis-ci/upload-test-report.sh
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
notifications:
  slack:
    secure: pYMytnSWqFOU0LPKEMQXzBpbOnTKUWtXJ/dNzyJl/wYuAou0JxPoGnpiWfV+f+Fws/iY5zZ2Rp4TYmQGAXDvD8D/QusAgGdCEp69zaw/wA7S/B94GZfyxMoSriP/RM9xK4bjQY1rsxBxtT12RP/5PyZ3DdO72mRwwQDDhPsyydFsYYl+cMF1ZsN+2yB4MF3yAt2jxliZDVg92mfn/ysG6RucbSWCN1QrgTzXzJeDdkoi54O3DpSnEDa9bRvDjfr7fiRuCR7VPYa/0lgRLjiggDP+Ie6D4JXnFFS/38MNTGREIbFW9i0DVP5KGbqAfpt/V4228YFrI7DPiY1+y4IEd0uYovDLi83fXQD3eD5bPW5Y2I+mh8TOJ3QJacx1crPyp7MPdIxdP7ifvbswhSlZ/8zWOJbbHJC0frSaSUfplBmfYHszSiEhsY2DmUqnIVr1Bm/Gb4kgxmQUjq6L4npGejEBGTzP7yt5q+u34Tugpijtp3nGUg5Vc6NfnojfZo3VkCS4uWa0GIiARUSVFZQFEJabrRQ3uo7DzJflgNg8YnhklwCKS0OwosKzwq1edq/Fcnz9JC3FAySW/rITLTpkSiOj8O7NquHxdbJ9q6+7wagPVFk/W4TD10MP1VIekmpTxUfwUDbVEsVSQeBfT3tbHYLcUYodgouMZnnqqNpPU3k=
